### ISSUE TITLE
maybe windows compatibility  in unreal 5.1.1?

### ISSUE THREAD

**Issue by MistarQ** [rangora/LumberJack#2]
it can not be compiled in unreal 5,
**unresolved external symbol _WSACleanup,**
it is  a windows compatibility problem i think.
i think i should put this question in unreal community and hope it will be fixed in new version.

by the way, it works well in unreal 4.24,
and really helps me a lot in learning unreal as a backend engineer.

**Comment by rangora** [comment]
It really to late..
this repository doesn't maintain due to it's just simple project for find a job.
However, I really glad to hear your learning something in my project.
I hope you what you do going well.
